name: pylint

on:
  push:
  pull_request:


concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true


jobs:
  lint:
    name: "${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      matrix:
        os:
          - "ubuntu"
          - "macos"
        python-version:
          - "3.10"
          - "3.11"
      fail-fast: false

    steps:
    - name: "Check out the repo"
      uses: "actions/checkout@v3"

    - name: "Set up Python ${{ matrix.python-version }}"
      uses: "actions/setup-python@v3"
      with:
        python-version: "${{ matrix.python-version }}"

    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install pydantic pylint pylint-pydantic pylint-pytest

    - name: "Analysing the code with pylint"
      run: |
        pylint monopoly tests run.py
